# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2019 Lars Povlsen <lars.povlsen@microchip.com>
#

obj-$(CONFIG_TARGET_SPARX5)	= ddr_umctl.o sparx5_reset.o ddr_aux.o
obj-$(CONFIG_SPL_BUILD)	= sparx5_spl.o

obj-$(CONFIG_ARMV8_PSCI) += sparx5_psci.o
